-- ==========================================
-- SQL Script for Setting Up Skills Table
-- ==========================================

-- 1. Create the `skills` table
CREATE TABLE public.skills (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    category text not null,
    category_icon text,
    icon text,
    percentage integer default 0,
    level text default 'beginner'::text
);

-- 2. Turn on Row Level Security (RLS)
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow public read access (SELECT)
CREATE POLICY "Public profiles are viewable by everyone."
ON public.skills FOR SELECT
USING ( true );

-- 4. Policy: Allow service role (admin) to INSERT/UPDATE/DELETE
-- The backend API accesses this table using the SUPABASE_SERVICE_ROLE_KEY
-- which overrides RLS by default. However, if your API uses the anon key,
-- you will need specific policies. Assuming service_role key is used for admin tasks,
-- the following policies are a best-practice safety net:

CREATE POLICY "Enable insert for authenticated users only" ON public.skills FOR INSERT WITH CHECK (auth.role() = 'service_role');
CREATE POLICY "Enable update for authenticated users only" ON public.skills FOR UPDATE USING (auth.role() = 'service_role');
CREATE POLICY "Enable delete for authenticated users only" ON public.skills FOR DELETE USING (auth.role() = 'service_role');

-- 5. Insert Initial Mock Data
INSERT INTO public.skills (name, category, category_icon, icon, percentage, level) VALUES
('JavaScript', 'Programming Languages', '<i class="fa-solid fa-code"></i>', '<i class="fa-brands fa-js"></i>', 90, 'expert'),
('Python', 'Programming Languages', '<i class="fa-solid fa-code"></i>', '<i class="fa-brands fa-python"></i>', 85, 'advanced'),
('Java', 'Programming Languages', '<i class="fa-solid fa-code"></i>', '<i class="fa-brands fa-java"></i>', 75, 'intermediate'),
('C#', 'Programming Languages', '<i class="fa-solid fa-code"></i>', 'C#', 70, 'intermediate'),
('React', 'Frameworks & Libraries', '<i class="fa-solid fa-layer-group"></i>', '<i class="fa-brands fa-react"></i>', 85, 'advanced'),
('Node.js', 'Frameworks & Libraries', '<i class="fa-solid fa-layer-group"></i>', '<i class="fa-brands fa-node-js"></i>', 80, 'advanced'),
('Express.js', 'Frameworks & Libraries', '<i class="fa-solid fa-layer-group"></i>', '<i class="fa-solid fa-server"></i>', 80, 'advanced'),
('Git', 'Tools & Technologies', '<i class="fa-solid fa-wrench"></i>', '<i class="fa-brands fa-git-alt"></i>', 90, 'expert'),
('Docker', 'Tools & Technologies', '<i class="fa-solid fa-wrench"></i>', '<i class="fa-brands fa-docker"></i>', 70, 'intermediate'),
('PostgreSQL', 'Databases', '<i class="fa-solid fa-database"></i>', '<i class="fa-solid fa-database"></i>', 80, 'advanced'),
('MongoDB', 'Databases', '<i class="fa-solid fa-database"></i>', '<i class="fa-solid fa-leaf"></i>', 75, 'intermediate');
